XGBClassifier:
  learning_rate: 0.2
  n_estimators: 1000
  max_depth: 5
  subsample: 1.0
  colsample_bytree: 0.9
  gamma: 0.2
  reg_alpha: 0.5
  reg_lambda: 0.1
  min_child_weight: 5
  eval_metric: 'logloss'
  early_stopping_rounds: 10
  tree_method: 'exact'